### ISSUE TITLE
Can you Add this one? I dont know why. But LEDs work with the Compiled firmware from Canable.io and with  this firmware they wont

### ISSUE THREAD

**Issue by brainbubblersbest** [SummerFalls/pcan_cantact#6]
You linked the oemdrv4.3.0 on your 1.6.3 release.
The Question about that are Obsolete ;D

**Comment by brainbubblersbest** [comment]
Seems to be Working you dont have to Explain. It just dowsnt seem to be on that Adapter here, but it does after try it with software and ignore the non working LEDs.


Its almost the same as the Canable, but with other LED Connectors. Can you add it to your Repository?
![DSDTECH SH-C30A](https://github.com/SummerFalls/pcan_cantact/assets/48190425/575fb972-810f-43f8-8897-3281c54f2633)

**Comment by SummerFalls** [comment]
Hello, @brainbubblersbest 

support for [DSD TECH SH-C30A](https://www.deshide.com/product-details.html?pid=384242&_t=1671089557) has been added now.

⚠️ **Note: According to the BOM table, SH-C30A uses a 24MHz crystal oscillator, so support for external 24MHz crystal oscillators is enabled in the firmware.**

https://github.com/SummerFalls/pcan_cantact/releases

![Pic](https://github.com/SummerFalls/pcan_cantact/assets/15645508/b5c4db48-6732-4473-8279-b7efcc0a3f53)

**Comment by brainbubblersbest** [comment]
I will test it. Do you know what versions from canapi2.dxl Pcanapi.dxl and pcan USB.sxs are compatible?
Trying for months to get it working together with codesxs2.3 over Cia dsp301 standard?

**Comment by SummerFalls** [comment]
Sorry, I don't know about that.
